version: "3"
services:
    app:
        container_name: nodejs
        restart: always
        build: ./
        links:
        - mongo
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        volumes:
        - ./data:/data/db
        ports:
        - "27017:27017"